import { defineConfig, globalIgnores } from 'eslint/config'

import reactConfig from '@another-graphql-ide/eslint-config/react'

export default defineConfig([
  reactConfig,
  // generated by @tanstack/router-plugin
  globalIgnores(['src/routeTree.gen.ts']),
  {
    languageOptions: {
      parserOptions: { tsconfigRootDir: import.meta.dirname },
    },
  },
])
