// Generated by react-foundry. Do not edit.
// Regenerated from the `nav` tree in your foundry config on every start.

declare module 'react-foundry' {
  interface Register {
    navPath: "UI Components" | "UI Components/Button" | "UI Components/Icon" | "UI Components/Icon Button" | "UI Components/Icon Button Group" | "UI Components/Input" | "UI Components/Pill" | "UI Components/Popover" | "UI Components/Resizer" | "UI Components/Separator" | "UI Components/Tabs" | "UI Components/Tooltip" | "UI Components/App Navigation Item" | "Navigation" | "Navigation/App Navigation" | "Navigation/Editor Group Tabs" | "Panes" | "Panes/Document Header" | "Panes/Response Header" | "Exported Components" | "Exported Components/Connection Bar" | "Exported Components/Editor" | "Exported Components/Editor Group" | "Exported Components/Headers Editor" | "Exported Components/Schema Tree" | "Exported Components/Schema Tree Settings" | "Exported Components/Schema Tree + Editor"
  }
}

// Marks this file as a module, which module augmentation requires.
export {}
